### PR TITLE
Create gnucash-3.7.ebuild

### PR DESCRIPTION
**Pull request by zdavatz**
see https://bugs.funtoo.org/browse/FL-6854

### CODE REVIEW

**Comment by zdavatz** [comment]
this helped a lot: https://www.youtube.com/watch?v=xUzjfyAZcq8&feature=youtu.be&t=994

**Comment by danielrobbins** [comment]
OK, but we do not use github currently for pull requests. We use code.funtoo.org.

**Comment by zdavatz** [comment]
You should use both. ;)

**Comment by danielrobbins** [comment]
Thank you for the suggestion. Closing this PR.

**Pull request closed without merging**
