### PR TITLE
unforking app-crypt/ccid as it is fixed upstream

### PR DESCRIPTION
**Pull request by palica**

### CODE REVIEW

**Comment by ghost** [comment]
the ccid is added for the requests of NRL, the ccid, pcsc-lite and pam_pkcs11

**Comment by ghost** [comment]
can you point what will be the fix for ccid

**Comment by palica** [comment]
image

SRC_URI fixed
funtoo SRC_URI unreachable
KEYWORDS change (not important for funtoo)
RDEPEND (lowest pcsc-lite)
```
ego query v pcsc-lite
 sys-apps/pcsc-lite| slot|               repo
-------------------+-----+-------------------
             1.8.22|    0| core-kit/1.2-prime
           * 1.8.23|     | core-kit/1.2-prime

ego query v pcsc-lite
 sys-apps/pcsc-lite| slot|               repo
-------------------+-----+-------------------
             1.8.22|    0| core-kit/1.0-prime
             1.8.23|     | core-kit/1.0-prime

```

Is this fork still needed?

**Comment by ghost** [comment]
Yes, its needed. I will fix SRC_URI

**Comment by palica** [comment]
does it have to be in curated? why can't it be in 1.x-prime branch? with all its deps?

**Pull request closed without merging**
